export default [
  {
    id: 1,
    area_depth1: "서울",
    area_depth2: [
      { id: 11, txt: "강남" },
      { id: 12, txt: "강남대로(씨티)" },
      { id: 13, txt: "강동" },
      { id: 14, txt: "군자" },
      { id: 15, txt: "더부티크 목동현대백화점" },
      { id: 16, txt: "동대문" },
      { id: 17, txt: "마곡" },
      { id: 18, txt: "목동" },
      { id: 19, txt: "상봉" },
      { id: 20, txt: "상암월드컵경지장" },
      { id: 21, txt: "성수" },
      { id: 22, txt: "센트럴" },
      { id: 23, txt: "송파파크하비오" },
      { id: 24, txt: "신촌" },
      { id: 25, txt: "이수" },
      { id: 26, txt: "창동" },
      { id: 27, txt: "코엑스" },
      { id: 28, txt: "홍대" },
      { id: 29, txt: "화곡" },
      { id: 30, txt: "ARTNINE" },
    ],
  },
  {
    id: 2,
    area_depth1: "경기",
    area_depth2: [
      { id: 31, txt: "고양스타필드" },
      { id: 32, txt: "광명AK플라자" },
      { id: 33, txt: "광명소하" },
      { id: 34, txt: "금정AK플라자" },
      { id: 35, txt: "김포한강신도시" },
      { id: 36, txt: "남양주" },
      { id: 37, txt: "남양주현대아울렛 스패이스원" },
      { id: 38, txt: "동탄" },
      { id: 39, txt: "미사강변" },
    ],
  },
  {
    id: 3,
    area_depth1: "인천",
    area_depth2: [
      { id: 41, txt: "검단" },
      { id: 42, txt: "송도" },
      { id: 43, txt: "영종" },
      { id: 44, txt: "인천논현" },
      { id: 45, txt: "청라지젤" },
    ],
  },
  {
    id: 4,
    area_depth1: "대전/충청/세종",
    area_depth2: [
      { id: 51, txt: "공주" },
      { id: 52, txt: "논산" },
      { id: 53, txt: "대전" },
      { id: 54, txt: "대전신세계 아트앤사이언스" },
      { id: 55, txt: "대전유성" },
      { id: 56, txt: "대전중앙로" },
      { id: 57, txt: "대전현대아울렛" },
      { id: 58, txt: "세종(조치원)" },
      { id: 59, txt: "세종나성" },
    ],
  },
  {
    id: 5,
    area_depth1: "부산/대구/경상",
    area_depth2: [
      { id: 61, txt: "경북도청" },
      { id: 62, txt: "경산하양" },
      { id: 63, txt: "경주" },
      { id: 64, txt: "구미강동" },
      { id: 65, txt: "김천" },
      { id: 66, txt: "남포항" },
      { id: 67, txt: "대구세븐밸리" },
      { id: 68, txt: "대구신세계(동대구)" },
      { id: 69, txt: "대구이시아" },
    ],
  },
  {
    id: 6,
    area_depth1: "광주/전라",
    area_depth2: [
      { id: 71, txt: "광주상무" },
      { id: 72, txt: "광주하남" },
      { id: 73, txt: "목포하당(포르모)" },
      { id: 74, txt: "순천" },
      { id: 75, txt: "여수웅천" },
      { id: 76, txt: "전대(광주)" },
      { id: 77, txt: "전주객사" },
      { id: 78, txt: "전주송천" },
      { id: 79, txt: "전주혁신" },
    ],
  },
  {
    id: 7,
    area_depth1: "강원",
    area_depth2: [
      { id: 81, txt: "남춘천" },
      { id: 82, txt: "속초" },
      { id: 83, txt: "원주혁신" },
      { id: 84, txt: "춘천석사" },
    ],
  },
  {
    id: 8,
    area_depth1: "제주",
    area_depth2: [
      { id: 91, txt: "제주삼화" },
      { id: 92, txt: "제주서귀포" },
      { id: 93, txt: "제주아라" },
    ],
  },
]